#!/usr/bin/env bash
set -e
HERE=$(realpath $(dirname $0))
NAME=barman-wrapper
DEST=/usr/local/bin/$NAME
SRC=$HERE/$NAME

if [[ -L $DEST && $(readlink -- $DEST) != $SRC ]]; then
    rm -f $DEST
fi

if [ ! -L $DEST ]; then
    echo "Creating link to $DEST to"
    echo "    $SRC"
    ln -s $SRC $DEST
    echo "Done!"
else
    echo "Already installed!"
fi
