# Use crontab.guru for testing cron expressions, e.g.:
# https://crontab.guru/#0_0_1_*_*
jobs:
  - name: barman-cron
    command: barman cron
    schedule: "* * * * *"
  - name: metrics
    command: barman-save-metrics
    schedule: "*/5 * * * *"
  - name: base-backup
    command: barman backup montagu
    schedule: "0 0 1 * *"
