#!/usr/bin/env bash
set -e
if which -a aws > /dev/null; then
	echo "AWS CLI is already installed."
else
	apt-get install awscli
fi

# required to install python sodium bindings (pynacl), which is a dependency
# of paramiko
# https://stackoverflow.com/a/36057779
apt-get install build-essential libssl-dev libffi-dev

pip3 install -r requirements.txt

echo "----------------------"
echo "Now run 'aws configure' as the user you will be running ./aws-barman as"
