#!/usr/bin/env bash
set -e
if which -a aws > /dev/null; then
	echo "AWS CLI is already installed."
else
	apt-get install awscli
fi

pip3 install -r requirements.txt

echo "----------------------"
echo "Now run 'aws configure' as the user you will be running ./aws-barman as"
